#--------------------------------------------------------------------------
# centos build environment
# 
# This Dockerfile will produce an image suitable for compiling software.
# The image will gave a C/C++ and Fortran compiler as well as python,
# It will also contain version control software (e.g. git and svn).
#
# To use this most effectively:
#
#      docker run -it --rm jeffersonlab/epsci-centos:7.9.2009 cat /container/dsh | tr -d "\r" > dsh
#      chmod +x ./dsh
#      ./dsh jeffersonlab/epsci-centos:7.9.2009
#
#--------------------------------------------------------------------------
#
#   docker build -t epsci-centos:7.9.2009 -t jeffersonlab/epsci-centos:7.9.2009 -f Dockerfile.centos.7.9.2009 .
#   docker push jeffersonlab/epsci-centos:7.9.2009
#
# On ifarm:
#   cd /scigroup/spack/mirror/singularity/images
#   singularity build epsci-centos-7.9.2009.img docker://jeffersonlab/epsci-centos:7.9.2009
#
#--------------------------------------------------------------------------

FROM centos:7.9.2009

# Install compiler and code management tools
RUN yum -y groupinstall 'Development Tools' \
	&& yum -y install python python3 git subversion cvs curl which

COPY dsh /container/dsh
COPY Dockerfile.centos.7.9.2009 /container/Dockerfile.centos.7.9.2009
RUN ln -s /root /home/root
RUN ln -s /root /home/0

CMD ["/bin/bash"]
