#--------------------------------------------------------------------------
# centos build environment
# 
# This Dockerfile will produce an image suitable for compiling software.
# The image will gave a C/C++ and Fortran compiler as well as python,
# It will also contain version control software (e.g. git and svn).
#
# To use this most effectively:
#
#      docker run -it --rm jeffersonlab/epsci-centos:7.9.2009 cat /container/dsh | tr -d "\r" > dsh
#      chmod +x ./dsh
#      ./dsh jeffersonlab/epsci-centos:7.9.2009
#
#--------------------------------------------------------------------------
#
# Multi-architecture builds:
# Use this if you want to build for both standard Intel/AMD architectures
# *and* for Apple silicon (M1 chip) architectures.
# Note: you only need to run the first command once to create a multi-arch
# builder on your local computer unless you remove it (last command).
#
#   docker buildx create --platform linux/arm64/v8,linux/amd64 --use --name mybuilder
#   docker buildx build --push --platform linux/arm64/v8,linux/amd64 -t jeffersonlab/epsci-centos:7.9.2009 -f Dockerfile.centos.7.9.2009 .
#   docker pull jeffersonlab/epsci-centos:7.9.2009
#   docker tag jeffersonlab/epsci-centos:7.9.2009 epsci-centos:7.9.2009
#   docker buildx rm mybuilder
#
#
# Single-architecture builds:
# The following will build only for the default architecture on your system.
#
#   docker build -t epsci-centos:7.9.2009 -t jeffersonlab/epsci-centos:7.9.2009 -f Dockerfile.centos.7.9.2009 .
#   docker push jeffersonlab/epsci-centos:7.9.2009
#
# On ifarm:
#   cd /scigroup/spack/mirror/singularity/images
#   singularity build epsci-centos-7.9.2009.img docker://jeffersonlab/epsci-centos:7.9.2009
#
#--------------------------------------------------------------------------

FROM centos:7.9.2009

# Install compiler and code management tools
RUN yum -y groupinstall 'Development Tools' \
	&& yum -y install python python3 git subversion cvs curl which

COPY dsh /container/dsh
COPY Dockerfile.centos.7.9.2009 /container/Dockerfile.centos.7.9.2009
RUN ln -s /root /home/root
RUN ln -s /root /home/0

CMD ["/bin/bash"]
