#--------------------------------------------------------------------------
# centos build environment
# 
# This Dockerfile will produce an image suitable for compiling software.
# The image will gave a C/C++ and Fortran compiler as well as python,
# It will also contain version control software (e.g. git and svn).
#
# To use this most effectively:
#
#      docker run -it --rm jeffersonlab/epsci-centos:8.3.2011 cat /container/dsh | tr -d "\r" > dsh
#      chmod +x ./dsh
#      ./dsh jeffersonlab/epsci-ubuntu-centos:8.3.2011
#
#--------------------------------------------------------------------------
#
#   docker build -t epsci-centos:8.3.2011 -t jeffersonlab/epsci-centos:8.3.2011 -f Dockerfile.centos.8.3.2011 .
#   docker push jeffersonlab/epsci-centos:8.3.2011
#
#   singularity build epsci-centos-8.3.2011.img docker://jeffersonlab/epsci-centos:8.3.2011
#
#--------------------------------------------------------------------------

FROM centos:8.3.2011

# Install compiler and code management tools
RUN dnf -y update \
	&& dnf -y groupinstall 'Development Tools' \
	&& dnf -y install gcc-gfortran python2 python3 git subversion curl \
	&& dnf clean all

COPY dsh /container/dsh
COPY Dockerfile.centos.8.3.2011 /container/Dockerfile.centos.8.3.2011
RUN ln -s /root /home/root
RUN ln -s /root /home/0

CMD ["/bin/bash"]
